# Generated by Django 3.1.4 on 2021-11-24 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(choices=[('radio', 'Переключатель.'), ('checkbox', 'Флажок.'), ('textbox', 'Ввод.')], default='radio', max_length=16)),
                ('score', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('answer_text', models.CharField(blank=True, max_length=32)),
                ('is_valid', models.BooleanField(default=False)),
                ('answer_input', models.CharField(blank=True, max_length=32)),
                ('valid_input', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('creation_date', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('limit_of_tries', models.SmallIntegerField(blank=True, default=1)),
                ('visible_valid_answers', models.BooleanField(blank=True, default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultsPassing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_time', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('answers', models.ManyToManyField(to='polls.Answer')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.exercise')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=128)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
        ),
    ]
